### ISSUE TITLE
Feature Request: Scrape Events for Specific Region

### ISSUE THREAD

**Issue by mgsgde** [francescov1/facebook-event-scraper#13]
Hi, do you plan to add a feature to scrape events for a specific region?

**Comment by francescov1** [comment]
Hey @mgsgde, what exactly do you mean? Are you referring to a way to fetch all events within a region?

Can you provide an example?

**Comment by mgsgde** [comment]
yes, for example extract a list of dance events from Europe and then navigate to each event's detail page and gather all relevant data step by step.

**Comment by francescov1** [comment]
I think that's out of scope for this tool. The main aim here is to scrape data for specific events, not to search for lists of events.

**Comment by bucinskasj** [comment]
@mgsgde you can create tools that "browse" Facebook events section for particular category, city combinations and then feed the event URLs into this library. The tool doesn't even need to go into the event directly, because the URLs are right within the HTML of the page and you can extract them with a simple regex.

**Comment by mgsgde** [comment]
> @mgsgde you can create tools that "browse" Facebook events section for particular category, city combinations and then feed the event URLs into this library. The tool doesn't even need to go into the event directly, because the URLs are right within the HTML of the page and you can extract them with a simple regex.

Thx for the tip. I tried [crawlee](https://crawlee.dev/) and it works well in combination with this tool.
